<?php

declare(strict_types=1);

namespace SBUERK\Seeder\Seeding\DataHandling;

use SBUERK\Seeder\Seeding\Definition\SeedDefinition;
use SBUERK\Seeder\Seeding\Exception\InvalidSeedDefinitionException;
use SBUERK\Seeder\Seeding\Exception\SeedingFailedException;
use SBUERK\Seeder\Seeding\Scenario\DataHandlerFactory;
use SBUERK\Seeder\Seeding\Scenario\DataHandlerWriter;
use TYPO3\CMS\Core\Authentication\BackendUserAuthentication;
use TYPO3\CMS\Core\DataHandling\DataHandler;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * Writes a composed scenario into the installation.
 *
 * This is what the scenario engine is missing to be usable outside a test run,
 * and every line of it is one of those things:
 *
 * - **The backend user has to be an administrator.** `DataHandler::insertDB()`
 *   honours a suggested uid only `if ($this->BE_USER->isAdmin() && …)` and
 *   ignores it silently otherwise, so a non-admin run would write the whole set
 *   under different uids than it declares and report success.
 * - **`DataHandler::$isImporting` is set.** It suppresses the automatic
 *   `autogenerated-<uid>` site configuration of `CreateSiteConfiguration`,
 *   which would otherwise be written for every seeded site root before the set
 *   gets to write its own.
 * - **`errorLog` becomes an exception.** `DataHandlerWriter` collects it and
 *   returns; a seed that half wrote itself has to fail loudly.
 * - **Files are written first.** They are indexed through the FAL API before
 *   any record is written, so a record naming a `sys_file` uid names one that
 *   exists.
 * - **File references are written last.** A `sys_file_reference` needs the uid
 *   of the record it hangs on, and `uid_foreign` is a plain integer column in
 *   which a placeholder would silently become `0` - see
 *   {@see FileReferenceSeeder}.
 *
 * This is a stateless service; the state of one run lives in the writer and in
 * the result object.
 *
 * @internal Part of the seeding implementation, not public API.
 */
final class ScenarioSeeder
{
    public function __construct(
        private readonly FileSeeder $fileSeeder,
        private readonly FileReferenceSeeder $fileReferenceSeeder,
    ) {}

    /**
     * @param array<string, true> $withoutSuggestedUids Suggestions to hold
     *        back, keyed `<table>:<uid>`, for a run that was forced past a uid
     *        collision.
     * @throws InvalidSeedDefinitionException
     * @throws SeedingFailedException
     */
    public function seed(
        SeedDefinition $definition,
        DataHandlerFactory $factory,
        BackendUserAuthentication $backendUser,
        array $withoutSuggestedUids = [],
    ): ScenarioSeedResult {
        if (!$backendUser->isAdmin()) {
            throw new SeedingFailedException(
                sprintf(
                    'Seeding "%s" requires an admin backend user: DataHandler honours a suggested uid only for'
                    . ' an admin and ignores it silently otherwise, which would write the seed with different uids'
                    . ' than it declares.',
                    $definition->identifier,
                ),
                1787075001,
            );
        }

        $dataMapPerWorkspace = $factory->getDataMapPerWorkspace();
        if ($dataMapPerWorkspace === []) {
            throw new SeedingFailedException(
                sprintf('The seed set "%s" contains no records.', $definition->identifier),
                1787075002,
            );
        }

        $fileUids = $this->fileSeeder->seed($definition);

        $dataHandler = GeneralUtility::makeInstance(DataHandler::class);
        $dataHandler->isImporting = true;

        // `DataHandlerWriter::withBackendUser()` is not used, for two reasons.
        // The DataHandler has to be reachable afterwards - `substNEWwithIDs` is
        // the only place the uid a record was written with can be read from -
        // and `isImporting` has to be set before the first `start()`. What that
        // named constructor adds on top, carrying `uc['copyLevels']` into
        // `DataHandler::$copyTree`, applies to a `copy` command; the command map
        // a scenario produces knows `move`, `delete` and `clearWSID` only.
        $writer = new DataHandlerWriter($dataHandler, $backendUser, $withoutSuggestedUids);
        $writer->invokeFactory($factory);

        $errors = $writer->getErrors();
        if ($errors !== []) {
            throw new SeedingFailedException(
                sprintf(
                    'Seeding "%s" failed: %s',
                    $definition->identifier,
                    implode(' | ', array_values(array_unique($errors))),
                ),
                1787075003,
            );
        }

        $result = new ScenarioSeedResult(
            writtenUids: $this->collectWrittenUids($dataMapPerWorkspace, $dataHandler),
            recordCounts: $this->countRecords($dataMapPerWorkspace),
            fileUids: $fileUids,
        );

        return $result->withReferenceUids(
            $this->fileReferenceSeeder->seed($definition, $result, $backendUser),
        );
    }

    /**
     * Maps what the scenario declared onto what was written.
     *
     * The data map is keyed by the `NEW…` identifier the factory generated and
     * carries the declared uid in `uid`; `DataHandler::$substNEWwithIDs` maps
     * that identifier to the uid the row ended up with. A record of a workspace
     * round whose key was already substituted has no entry there - it updated
     * an existing row rather than inserting one - and is passed over.
     *
     * @param array<int, array<string, array<string, array<string, mixed>>>> $dataMapPerWorkspace
     * @return array<string, int>
     */
    private function collectWrittenUids(array $dataMapPerWorkspace, DataHandler $dataHandler): array
    {
        $written = [];
        foreach ($dataMapPerWorkspace as $dataMap) {
            foreach ($dataMap as $tableName => $tableDataMap) {
                foreach ($tableDataMap as $identifier => $values) {
                    $declaredUid = (int)($values['uid'] ?? 0);
                    $writtenUid = (int)($dataHandler->substNEWwithIDs[$identifier] ?? 0);
                    if ($declaredUid < 1 || $writtenUid < 1) {
                        continue;
                    }
                    $written[$tableName . ':' . $declaredUid] = $writtenUid;
                }
            }
        }

        return $written;
    }

    /**
     * @param array<int, array<string, array<string, array<string, mixed>>>> $dataMapPerWorkspace
     * @return array<string, int>
     */
    private function countRecords(array $dataMapPerWorkspace): array
    {
        $counts = [];
        foreach ($dataMapPerWorkspace as $dataMap) {
            foreach ($dataMap as $tableName => $tableDataMap) {
                $counts[$tableName] = ($counts[$tableName] ?? 0) + count($tableDataMap);
            }
        }

        return $counts;
    }
}
