<?php

declare(strict_types=1);

namespace SBUERK\DataFactory\Seeding\DataHandling;

use Symfony\Component\DependencyInjection\Attribute\Exclude;

/**
 * What {@see SiteConfigurationSeeder} did, and what it found afterwards.
 *
 * The second half is the interesting one. Seeding suppresses the site
 * configuration TYPO3 writes by itself, unconditionally and not only when the
 * set declares `sites` - see {@see ScenarioSeeder}. That is right, because an
 * `autogenerated-<uid>` site is never what a seed wanted, but it turns a set
 * which seeds a site root and declares no site configuration into an instance
 * with a page tree and no frontend that can render it.
 *
 * Nothing in the writing path notices that, which is why it is collected here
 * rather than logged where it is found: the seeder has no output channel, the
 * command has, and a warning naming the root pages is the difference between
 * "this seed is incomplete" and "the frontend is broken and nothing said why".
 *
 * This is data, not a service.
 *
 * @internal Part of the seeding implementation, not public API.
 */
#[Exclude]
final readonly class SiteConfigurationSeedResult
{
    /**
     * @param list<string> $writtenSites The identifiers of the site
     *        configurations written, in the order the definition declares them.
     * @param list<int> $uncoveredSiteRoots The uids of the seeded pages that
     *        are site roots - on the page tree root, or carrying `is_siteroot` -
     *        and that no site configuration covers after the run, in ascending
     *        order. Empty is the normal case and the one that needs no
     *        reporting. A uid rather than a name because a scenario record has
     *        no symbolic identifier: what it declares is the uid itself.
     */
    public function __construct(
        public array $writtenSites = [],
        public array $uncoveredSiteRoots = [],
    ) {}
}
